apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: superhero-servicemonitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: superhero-app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - ${{ secrets.OPENSHIFT_PROJECT }}