 
drop table if exists super_hero cascade;

create table super_hero (
                            birthDate date,
                            creationDate date,
                            modified_date date,
                            id bigint generated by default as identity,
                            description varchar(255),
                            name varchar(100),
                            primary key (id)
);


INSERT INTO super_hero (name, description, birthDate, creationDate, modified_date)
VALUES
    ('Superman', 'The Man of Steel', '1938-04-18',  CURRENT_DATE(),  CURRENT_DATE()),
    ('Spider-Man', 'Your friendly neighborhood superhero', '1962-08-10',  CURRENT_DATE(),  CURRENT_DATE()),
    ('Wonder Woman', 'Amazonian princess with super strength', '1941-12-01',  CURRENT_DATE(),  CURRENT_DATE()),
    ('Batman', 'The Dark Knight of Gotham City', '1939-03-30',  CURRENT_DATE(),  CURRENT_DATE()),
    ('Captain America', 'The super-soldier with an unbreakable shield', '1941-03-01',  CURRENT_DATE(),  CURRENT_DATE()),
    ('Green Lantern', 'Guardian of Sector 2814 with a power ring', '1940-07-09',  CURRENT_DATE(),  CURRENT_DATE()),
    ('Black Widow', 'Master spy and skilled hand-to-hand combatant', '1964-04-04',  CURRENT_DATE(),  CURRENT_DATE());
