apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'superhero-app'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['localhost:{{ .Values.service.port }}']