drop table if exists super_hero cascade;

create table super_hero (
                            birthDate date,
                            creationDate date,
                            modified_date date,
                            id bigint generated by default as identity,
                            description varchar(255),
                            name varchar(100),
                            primary key (id)
);